name: HybridIslandPlugin
version: 1.0.0
main: HybridIslandPlugin\Main
api: [5.24.0]
author: YoungJun
description: SkyBlock 및 GridLand를 포함한 섬 관리 플러그인

permissions:
  hybridislandplugin.command.island:
    description: Island 명령어 사용 권한
    default: true
  hybridislandplugin.command.gridland:
    description: GridLand 명령어 사용 권한
    default: true
  hybridislandplugin.command.skyblock:
    description: SkyBlock 명령어 사용 권한
    default: true
