name: HybridIslandPlugin
version: 1.0.0
main: HybridIslandPlugin\Main
api: [5.24.0]
author: YoungJun
description: SkyBlock 및 GridLand를 포함한 섬 관리 플러그인

commands:
  island:
    description: 섬 관리 명령어
    usage: /island <create|delete|home|info>
    permission: hybridislandplugin.command.island
    aliases: [isl]
    subcommands:
      create: "섬 생성"
      delete: "섬 삭제"
      home: "섬으로 이동"
      info: "섬 정보 보기"
  gridland:
    description: GridLand 관리 명령어
    usage: /gridland <create|delete|home|info>
    aliases: [gl]
    permission: hybridislandplugin.command.gridland
    tabComplete: true
  skyblock:
    description: SkyBlock 관리 명령어
    usage: /skyblock <create|delete|home|info>
    aliases: [sb]
    permission: hybridislandplugin.command.skyblock
    tabComplete: true

permissions:
  hybridislandplugin.command.island:
    description: Island 명령어 사용 권한
    default: true
  hybridislandplugin.command.gridland:
    description: GridLand 명령어 사용 권한
    default: true
  hybridislandplugin.command.skyblock:
    description: SkyBlock 명령어 사용 권한
    default: true
